apiVersion: apps/v1

kind: Deployment

metadata:

  name: deploy-nginx

  labels:

    app: deploy-nginx

spec:

  replicas: 3

  selector:

    matchLabels:

      app: deploy-nginx

  template:

    metadata:

      labels:

        app: deploy-nginx

    spec:

      containers:

      - name: deploy-nginx

        image: nginx:1.15

        ports:
        - containerPort: 80