apiVersion: v1
kind: Service
metadata:
  name: svc-httpd
  labels:
    app: svc-httpd
spec:
  type: LoadBalancer
  ports:
    - name: svc-httpd
      port: 80
      targetPort: 80
  selector:
    app: deploy-httpd