apiVersion: apps/v1

kind: Deployment

metadata:

  name: deploy-database

  labels:

    app: deploy-database

spec:

  replicas: 3

  selector:

    matchLabels:

      app: deploy-database

  template:

    metadata:

      labels:

        app: deploy-database

    spec:

      containers:

      - name: mariadb

        image: mariadb:10.9

        ports:

        - containerPort: 80