apiVersion: v1
kind: Service
metadata:
  name: svc-database
  labels:
    app: svc-database
spec:
  type: LoadBalancer
  ports:
    - name: svc-database
      port: 3306
      targetPort: 3306
  selector:
    app: deploy-database