apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: argoproj/rollouts-demo
  newTag: "green"
- name: httpd
  newTag: "2.4.54"
- name: nginx
  newTag: "1.15"

resources:
  - deploy/blue/canary
  - deploy/blue/stable
  - deploy/green/canary
  - deploy/green/stable