apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-argorollout
  labels:
    app: deploy-argorollout
spec:
  replicas: 5
  selector:
    matchLabels:
      app: deploy-argorollout
  template:
    metadata:
      labels:
        app: deploy-argorollout
    spec:
      containers:
      - name: deploy-argorollout
        image: argoproj/rollouts-demo:blue
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
