apiVersion: v1
kind: Service
metadata:
  name: svc-argorollout
  labels:
    app: svc-argorollout  
spec:
  type: LoadBalancer
  ports:
    - name: svc-argorollout
      port: 80
      targetPort: http
      protocol: TCP      
  selector:
    app: deploy-argorollout
