apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-webserver
  labels:
    app: deploy-webserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deploy-webserver
  template:
    metadata:
      labels:
        app: deploy-webserver
    spec:
      containers:
      - name: deploy-webserver
        image: ghcr.io/kakaocloudschool/devops-test-web:714daec0
        ports:
        - containerPort: 80
