apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-webserver
  labels:
    app: webserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deploy-webserver
  template:
    metadata:
      labels:
        app: deploy-webserver
    spec:
      containers:
      - name: deploy-webserver
        image: nginx:1.19
        ports:
        - containerPort: 80