apiVersion: v1
kind: Service
metadata:
  name: svc-webserver
  labels:
    app: svc-webserver
spec:
  type: LoadBalancer
  ports:
    - name: svc-webserver
      port: 80
      targetPort: 80
  selector:
    app: deploy-webserver